manifest = "e79da93bf52fd79fc4419679e9a96ffafe6ac8beb8c22fa82a34d81fddd65a50"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-foreach"
target = "//:foreach"

[[dependency]]
package = "github.com/buckaroo-pm/boost-fusion"
target = "//:fusion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
target = "//:numeric_conversion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-parameter"
target = "//:parameter"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-ublas"
target = "//:ublas"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.58.0" ]
revision = "2d03b5bf34bf73cb2e4e2a7665c12cebb2d70890"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.58.0" ]
revision = "ac721f66265e383ac6d7b96996e902332d12783d"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.58.0" ]
revision = "91b063a3dc7abe79307276475ce8214d33408160"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.58.0" ]
revision = "f13bdc028f96f77a47386c5d4290205f5bd31d32"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.58.0" ]
revision = "ba2389bfd836700138f7fbd65858501d75276a05"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.58.0" ]
revision = "56d073a8276bae5f86b88b8e967da2e125280c0b"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.58.0" ]
revision = "a36f15fe51460b013e423ed1c83a0fcb719752ba"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.58.0" ]
revision = "2782837f081e7128e2c90d0318deeb6a1a56b782"

[lock."github.com/buckaroo-pm/boost-foreach"]
versions = [ "1.58.0" ]
revision = "b7d0988080afb32d07423f92d6cd8078322dcb3c"

[lock."github.com/buckaroo-pm/boost-fusion"]
versions = [ "1.58.0" ]
revision = "2a6590417b6317df6125d695edacee50167cc2e5"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.58.0" ]
revision = "6b05293620f9f352f8f37a482683dd888e5fbcd8"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.58.0" ]
revision = "38bbc6135995cb588347bf550798e80e73c09977"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.58.0" ]
revision = "4d4b55414dbb748251175df77ac6c3032cc79121"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.58.0" ]
revision = "f9f7db4f10577895e7cad767e6f6d7ebd87270c0"

[lock."github.com/buckaroo-pm/boost-parameter"]
versions = [ "1.58.0" ]
revision = "19600a2619454a08249f386f68ec2cf55a1b5783"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.58.0" ]
revision = "2b5f853e75e5811875cc344e5a6824cec279e9a7"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.58.0" ]
revision = "b875a58b71ad042b4fd1f1a4cf9ae338d776ff58"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "1.58.0" ]
revision = "4a10620fcf4bc8a93b9c8149640c6b10b728d590"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.58.0" ]
revision = "f777b1eef66c8145f13ab1077dc6585fbbb7f26a"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.58.0" ]
revision = "4d5c3a9eab5c2ab8391ad4c4308548c61d349727"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.58.0" ]
revision = "f8ab9ff6a62abd59ca5aee9f0f1b001efd024619"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.58.0" ]
revision = "7486c1bdd14951698025082023c90379990ed7fb"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.58.0" ]
revision = "707eee805b5b0c9f914b0cfb154d90609b119979"

[lock."github.com/buckaroo-pm/boost-ublas"]
versions = [ "1.58.0" ]
revision = "77502fccdc1677fc1b3d1882f340ac592ff4d002"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.58.0" ]
revision = "464be14cff1e4aa654507df1a6313d366a45d974"
