manifest = "64eb1110b5119480ef0487668fc4c448c5e2da9d20fb3130fe7e3d9f73c0f375"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-foreach"
target = "//:foreach"

[[dependency]]
package = "github.com/buckaroo-pm/boost-fusion"
target = "//:fusion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
target = "//:numeric_conversion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-parameter"
target = "//:parameter"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-ublas"
target = "//:ublas"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.64.0" ]
revision = "ed616b98f03f533e08b0fdfc7b7ea04e5d9be1d2"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.64.0" ]
revision = "e3fa47a21cd2ac5e967de7a1ce612ff22aef9196"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.64.0" ]
revision = "53cb8f97ebf8136769d264c30ad7b9c4d86d4442"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.64.0" ]
revision = "34e26afff84223fcbe4fa68df038cc152b372105"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.64.0" ]
revision = "9cbe0f1be39466ec9b76b35b81295959fd417de0"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.64.0" ]
revision = "d2d531ddc041d4f15d72a5932846557e873422a4"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.64.0" ]
revision = "fea9d446679bef8b8273c3c71c9dbf9af5f4ee1d"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.64.0" ]
revision = "4c80254b6405c7300c1bfedc73fd0fb020e7d1ee"

[lock."github.com/buckaroo-pm/boost-foreach"]
versions = [ "1.64.0" ]
revision = "8224f0a72bfe5f18b9c7044691d70f42ca723e20"

[lock."github.com/buckaroo-pm/boost-fusion"]
versions = [ "1.64.0" ]
revision = "5a856f4063cd282a33b06081a9bcd4ea3d540056"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.64.0" ]
revision = "2c5699a79433c947c9bdc113e914afc7d635ce3d"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.64.0" ]
revision = "914dce03ef4cc36ec725d691ed33910cb28f0784"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.64.0" ]
revision = "b5db1c11e9d7d056458e2e2495598d346fdbad8b"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.64.0" ]
revision = "b6945f2c07ca4d86746f87a06ca23c968ca1ef61"

[lock."github.com/buckaroo-pm/boost-parameter"]
versions = [ "1.64.0" ]
revision = "2ad6161cd777b393f5247f9a4d1b23c200c2ed62"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.64.0" ]
revision = "db820029d840e07d89f1e4d0faadbeec6ea0b3d4"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.64.0" ]
revision = "153b1b1eff9aa64f7922f68e25d612b7186fd9db"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "1.64.0" ]
revision = "a9a47753013c5a09557ccc214482b923ac2bfcae"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.64.0" ]
revision = "0389fa64af0a06cd7aa48c6269713917398dc308"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.64.0" ]
revision = "b182b5c6595c12a5317584171d742a2dc1ce3c80"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.64.0" ]
revision = "35287c284136dc8746bf838e8be05d1510eb3542"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.64.0" ]
revision = "5f89ad27dfc00eea2b01924db8a5e39ebaeec966"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.64.0" ]
revision = "d6dca9615f2a9736e23db6faf9870596930c8a02"

[lock."github.com/buckaroo-pm/boost-ublas"]
versions = [ "1.64.0" ]
revision = "5c0ffc09f0620c4a5b9df9dae3802ff4d066f943"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.64.0" ]
revision = "96b85585532e8a6ac453b83ae19ac6193ad41e30"
